### ISSUE TITLE
Create module to handle the Arduino Uno - merge with #14

### ISSUE THREAD

**Issue by bttner** [EricssonResearch/arms#10]
The Arduino Uno is among others used for the purpose of:
- Sending sensor data to the Raspberry Pi.
- Fulfilling the task of gripping an obstacle. A respective command is sent by the Raspberry Pi. 

To be able to handle these query and command requests a respective module should be implemented. Further requirements have to be investigated and stated here.

 In addition, tests should show that this module works as intended.

**Comment by johandanmo** [comment]
Useful code has been done previously and is on Drive
https://drive.google.com/drive/folders/1WJE50lIOPbDKrnzgYaHyFqVUHfzDOrvW?usp=sharing
