### ISSUE TITLE
Create an Arduino Class

### ISSUE THREAD

**Issue by ersve** [EricssonResearch/arms#14]
A class that handles communication between the Raspberry pi and the Arduino UNO.

**Requirements**

0. The Arduino Class shall establish a two-way connection with the Arduino UNO using Serial communication.

1. The Arduino Class shall be able to terminate  the Serial communication with  Arduino UNO.

2. When establishing/initializing connection with the Arduino UNO, the Arduino Class shall fetch the necessary information, such as IP-adress, Port etc. from the config.json file.

3. If the config.json file cannot be accessed, then the Arduino Class shall use predefined values.

4.  The methods in the Arduino Class shall be comprised of Commands that are sent to the Arduino UNO for execution.

5. All messages, both sent and received, shall be of type: string, with values separated by a comma (',') in the following format: {ID} , {data_length} , {data}.
ID, data_length, data are integers. In case of multiple datapoints, these shall be separated by a semicolon (';'). For example a message with ID = 3, data_length = 2 and data = 19.7 23.9 will look like this: "3,2,19.7;23.9,".

6. The Ardunio class shall contain methods:

   - Close gripper
   - Open gripper
   - Request a Status from the Arduino UNO

**Comment by bttner** [comment]
Really nice work, but there is already an issue for that, see issue #10. I think we should merge them together and delete one.

**Comment by ersve** [comment]
@bttner We interpreted issue #10 as the code to be run on the Arduino. Because it talks about both the units. This issue is only related to the Rpi-side of the problem.

**Comment by bttner** [comment]
@ersve I see, maybe I was too imprecise. The label "language: Python" should have indicated that it runs on the Raspberry Pi, but apparently it didn't work out. Nevermind, that can be fixed easily.

**Comment by johandanmo** [comment]
Useful code done previously 
https://drive.google.com/drive/folders/1WJE50lIOPbDKrnzgYaHyFqVUHfzDOrvW?usp=sharing
