### ISSUE TITLE
Arduino Class - Function: getTranslation

### ISSUE THREAD

**Issue by ersve** [EricssonResearch/arms#15]
Main issue #14 

Description:
This function calculates the amount of revolutions and direction for the stepper motor to reach a certain distance between the pinchers.

INPUT: 
- Desired pincer distance
- Current pincer distance

OUTPUT: 
- Motor pulses: The amount of pulses needed by the stepper motor to reach the desired distance
- Motor direction: The direction of rotation (clockwise or counter-clockwise)

**Comment by Chryloz** [comment]
Code exists, but won't be called upon. Instead, gripper gets calibrated to known point, and rPi keeps track of number of pulses sent in both directions to ensure it doesn't go out of bounds. The actual control-flags for out-of-bounds is not done, however deemed unnecessary for this project
