### ISSUE TITLE
Arduino Class - Function: receive

### ISSUE THREAD

**Issue by ersve** [EricssonResearch/arms#19]
Main issue #14

**Description:**
Receives a message from the Arduino UNO sent to the Raspberry pi. The function receives messages according to the protocol and reconstructs it into a readable string. This means it will format the message into an actionable item.

**INPUT:**
- NONE

**OUTPUT:**
- Function identifier
- Message

**Comment by Chryloz** [comment]
Obsolete, the program asynchronously listens for messages from the Arduino. A receive function does exist which is not called upon. It displays the last received message
