### ISSUE TITLE
Arduino UNO Main

### ISSUE THREAD

**Issue by ersve** [EricssonResearch/arms#29]
This is the main code running on the Arduino UNO platform. The platform will handle the stepper motor on the gripper, the force sensor on the pincer and communicate with the Raspberry pi via a serial connection.

**Requirements**
0. All configurations/initializations shall be done on the Arduino UNO.
1. Communication with rPi shall be done via serial.
2. When a message arrives from the rPi, the targeted part/function of the code will be run.
3. The message to be interpreted shall contain an identifier ID which specifies the function to be run, length of the data, as well as the necessary input variables.
4. All messages, both sent and received, shall be of type: string, with values separated by a comma (',') in the following format: {ID} , {data_length} , {data}.
ID, data_length, data are integers. In case of multiple datapoints, these shall be separated by a semicolon (';'). For example a message with ID = 3, data_length = 2 and data = 19.7  23.9 will look like this: "3,2,19.7;23.9,".
5. The Arduino UNO Main shall control the stepper motor by influencing the connected driver.
6. The Arduino UNO Main shall interpret the values given by the pressure sensor.
7. When requested by the rPi, the Arduino UNO Main shall send a current status message to the rPi.

**Comment by johandanmo** [comment]
The majority of these tasks are done and is on Drive
