### ISSUE TITLE
Create class for serial communication

### ISSUE THREAD

**Issue by bttner** [EricssonResearch/arms#9]
To be able to connect for instance with the Arduino Uno via serial communication, a respective class should be introduced. Requirements:
- At least the device name (port) has to be loaded from the config file (_arms/config.config.json_), so it can be changed easily.
- Ability to:
   - Send and receive messages.
   - Close the connection.
- This class should be variable in the sense that it can establish a connection to several given ports and therefore several devices at the same time.

In addition, appropriate tests should be included.

**Comment by cyberhobbes** [comment]
Hi Felix,

I could give this a try.

Some questions:
1. Is the configuration json going to be in arms/config/config.json? Not sure if it was a typo.
2. Since it is a class, we should be able to call the class with different ports. Did I understand the third item correctly?

**Comment by johandanmo** [comment]
See Drive
https://drive.google.com/drive/folders/1WJE50lIOPbDKrnzgYaHyFqVUHfzDOrvW?usp=sharing

**Comment by ersve** [comment]
The module pySerial already has all of these attributes, except loading from the config file. This is something that instead could be realized in the Arduino class #14  directly.
